#!/bin/bash
# download and unzip 79 ENCODE cell line bedgraphs for C3D database.

wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseA549Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAg04449Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAg04450Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAg09309Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAg09319Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAg10803Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseAoafAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseBe2cAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseBjAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseCaco2Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseCmkAln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseGm06990Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseGm12864Aln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseGm12865Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseGm12878Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseH1hescAln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseH7esAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHacAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHaeAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHahAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHaspAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHbmecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHcfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHcfaaAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHcmAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHconfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHcpeAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHct116Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHeeAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHelas3Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHepg2Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHffAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHffmycAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHgfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHipeAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHl60Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecdbladAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecdblneoAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecdlyadAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecdlyneoAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecdneoAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmveclblAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHmvecllyAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHnpceAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHpafAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHpdlfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHpfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHrceAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHreAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHrgecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHrpeAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHsmmAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHsmmtAln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHuvecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseHvmfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseJurkatAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseK562Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseLncapAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseMcf7Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseMonocd14Aln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNb4Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNhaAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNhdfadAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNhdfneoAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNhekAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseNhlfAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnasePanc1Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseRptecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseSaecAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseSkmcAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseSknmcAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseSknshraAln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseTh1Aln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseTh2Aln_1Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseWerirb1Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseWi38Aln_2Reps.norm5.rawsignal.bedgraph.gz
wget http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/supplementary/integration_data_jan2011/byDataType/signal/jan2011/bedgraph/wgEncodeUwDnaseWi38OhtamAln_2Reps.norm5.rawsignal.bedgraph.gz
